#Today we learned how input and variables work, and how to include them with the print function.
print("We gonna try some inputs!")
input("Hello?")
print("Cool I can type in the console!")

print("Now some variables.")
Question1 = input("I don't want to ask you your name, yet here we are. So... What's your name?")
Question2 = input("Now, How old are you? Ya, that's right, I'm asking you your age. Watcha gonna do about it, huh?")
Question3 = input("Do you like Replit? I think it's fine. My friends are ahead of me in this and I'm kinda concerned.")

print()
print("You are the one they call:")
print(Question1)
print("You're only:")
print(Question2)
print("And you believe that replit is:")
print(Question3)
print("Cool.")

print("Working on errors now")
myvariable = input("WHO GOES THERE? ")
print(myvariable)

print()
print("I'm lazy now so I'm just going to copy paste for the rest of this one")
print()

myGrandma = input("How's your Grandma doing? 😘 ")
print(myGrandma)
myLunch = input("What are you having for lunch? ")
print("Hmm, it sounds like you really should just order")
print(myLunch)
print("as soon as possible!")

print()

print("Definitely not a Phishing Scam")
print()
input("Your Name")
print("Thanks for logging in")
print(Question1)
cardNumber = input("What is your credit card number?")
print("Thanks, I definitely wont put")
print("cardNumber")
print("into Amazon and order anything weird")
print()
print("Promise")
maidenName = input("What is your Mother's maiden name? ")
print()
print("That's cool, I just wanted to know that")
print(maidenName)
print("was your Mum's maiden name. Not because the bank requested it or anything, honest.")

print()
print("Challenge time.")
print()

Name = input("What's your name?")
Food = input("What's your favorite food?")
Music = input("What's your favorite music?")
Live = input("Where do you live?")
print()
print("So your name is...")
print(Name)
print("And you like...")
print(Food)
print("And you listen to...")
print(Music)
print("And you live in...")
print(Live)
print("Cool.")
